#!/bin/bash -f
#################################################################
# Script to write distribution tar file of KRC system
#  step3  script[s] must be executed first
#_Hist 2005jan25 Hugh Kieffer
# 2009may12 HK minor cleanup
# 2011oct17 HK Make generic
# 2013oct2 HK Move BIG to step4b
# 2017feb25 HK Convert from tsch to bash and add test on Makefile
#################################################################

RT1='/work2/'		# one level above distribution constuction area
RT2='DistKRC'		# distribution construction area
NAME='krc' 			# name for this distribution
SKEL='dist.tar.gz'		# last part of tar file name	
# SKEB='big.tar'       # last part of BIG tar file name
  
# name construction
IN=$RT1$RT2			# construction area
OUT=$RT1$NAME$SKEL 		# output tar file
# OBIG=$RT1$NAME$SKEB 	# output tar file

echo "IN="$IN
echo "OUT="$OUT

cd $IN

diff ~/krc/src/Makefile $IN'/src/Makefile'
echo " Above diff should have only lines with trailing #<> and those"
echo " should be identical except for leading space or # . Is this true?  "
read -p  " y/n > " resp 
if [[ $resp != 'y' ]]; then  #  
    echo "resp= "$resp   #t display what was obtained
    echo "Edit ~/krc/src/MakefileDist as needed and rerun step3"
    exit
fi

tar -chzf  $OUT aaa doc idl run src  	 # tar following all links

#echo "OBIG="$OBIG
#tar -chf  $OBIG big	 # tar following all links	
	
pwd
cd ~/krc/aaa   # return to parent directory
pwd

echo "Now:  mv "$OUT"  KRC/krc---.tar.gz"
exit